title: Oakland Pride
email: info@oaklandpride.org
description: Celebrating the LGBTQ+ community in Oakland, California. Save the date for Oakland Pride 2026!
baseurl: ""
url: "oaklandpride.org"
website: https://oaklandpride.org
twitter_username: oaklandpride
github_username:  oaklandpride

permalink: /:categories/:year/:month/:day/:title/

pride-theme: "Coming Soon 2026"
eventdates: "September 2026 - Date TBA"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

sass:
  load_paths:
    - assets
    - vendor/bundle/ruby/3.4.0/gems/bootstrap-5.3.5/assets/stylesheets/
    - vendor/bundle/ruby/3.2.0/gems/bootstrap-5.3.5/assets/stylesheets/
  style: compressed


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
